version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  redis:
    image: redis:7
    restart: always
    container_name: redis_app

  web:
    build: .
    env_file:
      - .env.prod
    container_name: backend
    command: ["/app/docker/app.sh"]
    volumes:
      - /var/www/market/media:/app/media
      - /var/www/market/sttaic:/app/static
    ports:
      - "6000:6000"
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env.prod
    container_name: celery_app
    command: ["./docker/celery.sh"]
    depends_on:
      - redis

  

volumes:
  postgres_data: