# Generated by Django 5.0 on 2023-12-21 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='Лого')),
                ('author', models.CharField(max_length=256, verbose_name='Автор')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.JSONField(blank=True, default={})),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256, verbose_name='Название компании')),
                ('fullName', models.CharField(max_length=256, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=256, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=256, verbose_name='Менеджер')),
                ('delivery_condition', models.CharField(max_length=256, verbose_name='Условия доставки')),
                ('map_visor', models.CharField(max_length=256, verbose_name='Отображение на карте')),
                ('contract', models.CharField(max_length=256, verbose_name='Договор')),
                ('site', models.CharField(max_length=256, verbose_name='Сайт')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для выгрузок')),
                ('work_time', models.CharField(max_length=256, verbose_name='Часы работы')),
                ('assembly_time', models.CharField(max_length=256, verbose_name='Время сборки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.provider', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(max_length=256, verbose_name='Артикул')),
                ('name', models.CharField(max_length=256, verbose_name='Название товара')),
                ('image', models.ImageField(upload_to='product', verbose_name='Фото')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('units', models.CharField(choices=[('см', 'Сантиметры'), ('шт', 'Штук')], max_length=10, verbose_name='Ед. изм')),
                ('remainder', models.PositiveIntegerField(verbose_name='Остаток')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Категория')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
