# Generated by Django 4.2.8 on 2024-05-29 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=256, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=256, unique=True, verbose_name='Номер телефона')),
                ('cart', models.JSONField(blank=True, default={})),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='DeliveryCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Условия доставки')),
            ],
            options={
                'verbose_name': 'Условия доставки',
                'verbose_name_plural': 'Условия доставки',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='users/logo')),
                ('status', models.CharField(choices=[('free', 'Частник'), ('store', 'Магазин'), ('hyper', 'Гипермаркет')], default='free', max_length=256, verbose_name='Статус')),
                ('status_time', models.DateTimeField(blank=True, null=True)),
                ('company', models.CharField(default='', max_length=256, verbose_name='Название компании')),
                ('fullName', models.CharField(max_length=256, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=256, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('site', models.URLField(default='', verbose_name='Сайт')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('visible_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.provider')),
            ],
            options={
                'verbose_name': 'Бегущая строка',
                'verbose_name_plural': 'Бегущая строка',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=256, verbose_name='Название магазина')),
                ('map_visor', models.CharField(max_length=256, verbose_name='Отображение на карте')),
                ('contract', models.CharField(default='', max_length=256, verbose_name='Договор')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес склада для самовывоза')),
                ('phone', models.CharField(max_length=256, verbose_name='Контакты для заказа')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для выгрузок')),
                ('work_time_from', models.TimeField(verbose_name='Часы работы от')),
                ('work_time_to', models.TimeField(verbose_name='Часы работы до')),
                ('assembly_time', models.CharField(max_length=256, verbose_name='Время сборки')),
                ('approve', models.BooleanField(default=False)),
                ('delivery_conditions', models.ManyToManyField(to='core.deliverycondition', verbose_name='Условия доставки')),
                ('payment_methods', models.ManyToManyField(to='core.paymentmethod', verbose_name='Способ оплаты')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider', verbose_name='Продавец')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Запросы',
            },
        ),
        migrations.CreateModel(
            name='ProviderOrder',
            fields=[
                ('type', models.CharField(max_length=256)),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('ticker', models.TextField(blank=True, null=True)),
                ('ticker_days', models.PositiveIntegerField(blank=True, null=True)),
                ('news', models.TextField(blank=True, null=True)),
                ('payment_id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.provider')),
            ],
            options={
                'verbose_name': 'Заказы поставщика',
                'verbose_name_plural': 'Заказы поставщика',
            },
        ),
        migrations.CreateModel(
            name='ProviderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='users/file')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articul', models.CharField(blank=True, max_length=256, null=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=500, verbose_name='Название товара')),
                ('image', models.ImageField(upload_to='product', verbose_name='Фото')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('unit', models.CharField(choices=[('см', 'см'), ('шт', 'шт'), ('м2', 'м2')], max_length=10, verbose_name='Ед. изм')),
                ('remainder', models.PositiveIntegerField(verbose_name='Остаток')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Категория')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store', verbose_name='Магазин')),
                ('tags', models.ManyToManyField(to='core.tag')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('delivery_date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('checkk', models.FileField(blank=True, null=True, upload_to='check')),
                ('check_date', models.DateTimeField(blank=True, null=True)),
                ('accept', models.DateTimeField(blank=True, null=True)),
                ('transit', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.PositiveIntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.buyer')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.deliverycondition')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.provider')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.store')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.provider')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
