# Generated by Django 4.2.8 on 2024-01-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='ads/market.png', upload_to='ads', verbose_name='Фото')),
                ('title', models.CharField(default='Todotodo Market', max_length=256, verbose_name='Заголовок')),
                ('text', models.TextField(default='Здесь может быть ваша релама', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Бегущая строка',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
