# Generated by Django 4.2.8 on 2024-04-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='status',
            field=models.CharField(choices=[('free', 'Частник'), ('store', 'Магазин'), ('hyper', 'Гипермаркет')], default='free', max_length=256, verbose_name='Статус'),
        ),
    ]
