# Generated by Django 4.2.8 on 2024-06-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerorder',
            name='ticker_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticker',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
