# Generated by Django 4.2.8 on 2023-12-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='units',
            new_name='unit',
        ),
    ]
