# Generated by Django 4.2.8 on 2024-06-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_providerorder_ticker_link_ticker_counter_ticker_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(default='', max_length=256, verbose_name='Адрес компании'),
        ),
    ]
