# Generated by Django 4.2.8 on 2024-04-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checked',
        ),
        migrations.AddField(
            model_name='order',
            name='checkk',
            field=models.FileField(blank=True, null=True, upload_to='check'),
        ),
    ]
