# Generated by Django 4.2.8 on 2024-04-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_provider_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'Бегущая строка', 'verbose_name_plural': 'Бегущая строка'},
        ),
    ]
