# Generated by Django 4.2.8 on 2024-06-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_provider_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='approve',
            field=models.BooleanField(default=True),
        ),
    ]
