# Generated by Django 4.2.8 on 2024-04-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ads_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Способ оплаты')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
        migrations.RemoveField(
            model_name='store',
            name='delivery_condition',
        ),
        migrations.AddField(
            model_name='store',
            name='payment_method',
            field=models.ManyToManyField(to='core.paymentmethod', verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_condition',
            field=models.ManyToManyField(to='core.deliverycondition', verbose_name='Условия доставки'),
        ),
    ]
