# Generated by Django 4.2.8 on 2023-12-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_units_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='articul',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('см', 'Сантиметры'), ('шт', 'Штук'), ('м2', 'м2')], max_length=10, verbose_name='Ед. изм'),
        ),
    ]
