# Generated by Django 4.2.8 on 2024-06-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_store_approve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='address',
        ),
    ]
