# Generated by Django 4.2.8 on 2024-04-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentmethod_remove_store_delivery_condition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='delivery_condition',
            new_name='delivery_conditions',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='payment_method',
            new_name='payment_methods',
        ),
    ]
