# Generated by Django 4.2.8 on 2024-06-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_provider_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='total_price',
        ),
    ]
